In [3]:
import numpy as np
import tensorflow as tf
import pandas as pd
import keras
from tensorflow.keras import Sequential
from keras.layers import Dense

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
dataset['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [12]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

C:\Users\LISHA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\LISHA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [17]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [24]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.6450 - acc: 0.6434
Epoch 2/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.5102 - acc: 0.7964
Epoch 3/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.4754 - acc: 0.7999
Epoch 4/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4527 - acc: 0.8037
Epoch 5/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4373 - acc: 0.8060
Epoch 6/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4259 - acc: 0.8080
Epoch 7/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.4168 - acc: 0.8133
Epoch 8/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4087 - acc: 0.8184
Epoch 9/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4015 - acc: 0.8205
Epoch 10/100
8000/8000 [===================

8000/8000 [==============================] - 1s 79us/sample - loss: 0.3309 - acc: 0.8650
Epoch 79/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.3313 - acc: 0.8644
Epoch 80/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3304 - acc: 0.8643
Epoch 81/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.3307 - acc: 0.8639
Epoch 82/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3302 - acc: 0.8655
Epoch 83/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3302 - acc: 0.8643
Epoch 84/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.3296 - acc: 0.8650
Epoch 85/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3296 - acc: 0.8639
Epoch 86/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.3298 - acc: 0.8658
Epoch 87/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3296 - acc: 

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1511   84]
 [ 188  217]]
